<?php
namespace App\Http\Controllers;
use App\Exports\ActivitiesExport;use App\Exports\PdfActivitiesExport;use Illuminate\Http\Request;use Maatwebsite\Excel\Facades\Excel;
class ReportController extends Controller{
 private array $columns=['activity_date'=>'Date','created_at'=>'Logged At','title'=>'Activity','category'=>'Category','description'=>'Description','priority'=>'Priority','status'=>'Status','started_at'=>'Start Time','completed_at'=>'End Time','duration_minutes'=>'Duration (min)','outcome'=>'Outcome','blockers'=>'Blockers','follow_up_required'=>'Follow-up','follow_up_action'=>'Next Action','reference_number'=>'Reference','evidence_url'=>'Evidence URL'];
 public function index(Request $r){$default=$r->user()->reportPreferences()->where('is_default',true)->first();$selected=$this->list($r->input('columns',$default?->columns??['activity_date','title','category','status','outcome']));$order=$this->list($r->input('order_json',$default?->column_order??$selected));$selected=array_values(array_intersect($selected,array_keys($this->columns)));$order=array_values(array_filter($order,fn($x)=>in_array($x,$selected,true)));foreach($selected as $x)if(!in_array($x,$order,true))$order[]=$x;return view('reports.index',['columns'=>$this->columns,'selected'=>$selected,'order'=>$order]);}
 public function savePreference(Request $r){$d=$r->validate(['name'=>'required|string|max:100','columns'=>'required|array','order'=>'required|array','is_default'=>'nullable|boolean']);$c=array_values(array_intersect($d['columns'],array_keys($this->columns)));$o=array_values(array_filter($d['order'],fn($x)=>in_array($x,$c,true)));if($r->boolean('is_default'))$r->user()->reportPreferences()->update(['is_default'=>false]);$r->user()->reportPreferences()->create(['name'=>$d['name'],'columns'=>$c,'column_order'=>$o,'is_default'=>$r->boolean('is_default')]);return back()->with('success','Report layout saved.');}
 public function export(Request $r,string $format){abort_unless(in_array($format,['xlsx','csv','pdf'],true),404);$c=$this->list($r->input('columns','activity_date,title,category,status,outcome'));$o=$this->list($r->input('order',$c));$c=array_values(array_intersect($c,array_keys($this->columns)));$o=array_values(array_filter($o,fn($x)=>in_array($x,$c,true)));foreach($c as $x)if(!in_array($x,$o,true))$o[]=$x;$from=$r->input('from',now()->startOfMonth()->toDateString());$to=$r->input('to',now()->endOfMonth()->toDateString());$e=new ActivitiesExport($r->user(),$from,$to,$o);if($format==='xlsx')return Excel::download($e,'it-activity-report.xlsx');if($format==='csv')return response()->streamDownload(function()use($e){echo $e->toCsv();},'it-activity-report.csv',['Content-Type'=>'text/csv']);return app(PdfActivitiesExport::class)->download($r->user(),$from,$to,$o,$this->columns);}
 private function list($v):array{if(is_array($v))return array_values(array_filter($v));if(is_string($v)){$j=json_decode($v,true);if(is_array($j))return array_values(array_filter($j));return array_values(array_filter(array_map('trim',explode(',',$v))));}return[];}
}
